MyUSER="root"
MyPASS="iloverandompasswordsbutthiswilldo"
HostName="localhost"
dbName="hospital"
dbUser="hsuser"
dbPass="root"
mysql -u $MyUSER -h $HostName -p$MyPASS -Bse "CREATE USER '$dbUser'@'*' IDENTIFIED BY '$dbPass';"
mysql -u $MyUSER -h $HostName -p$MyPASS -Bse "CREATE DATABASE $dbName;"
mysql -u $MyUSER -h $HostName -p$MyPASS -Bse "GRANT ALL ON ${dbName}.* to '$dbUser' identified by '$dbPass';"